### ISSUE TITLE
Support for relations (feature request)

### ISSUE THREAD

**Issue by lovetoburnswhen** [lfvilella/pydantic2graphene#41]
Specifically relations between Pydantic models eg
```python
class A(BaseModel):
	name: str

class B(BaseModel):
	a: A
```

**Comment by lfvilella** [comment]
Hi @lovetoburnswhen feature you are requesting it's been around since first version package, please check out [test_complex_conversions](https://github.com/lfvilella/pydantic2graphene/blob/v0.3.1/tests/converter_helper/test_complex_conversions.py#L24) to get some examples, we could certainly do a better job documenting it, PRs are welcomed.
